a = float(input('Digite um número para ver sua tabuada:'))
print('-' * 12)
print('{:.0f} x  1 = {:.0f}'.format(a, a))
print('{:.0f} x  2 = {:.0f}'.format(a, a*2))
print('{:.0f} x  3 = {:.0f}'.format(a, a*3))
print('{:.0f} x  4 = {:.0f}'.format(a, a*4))
print('{:.0f} x  5 = {:.0f}'.format(a, a*5))
print('{:.0f} x  6 = {:.0f}'.format(a, a*6))
print('{:.0f} x  7 = {:.0f}'.format(a, a*7))
print('{:.0f} x  8 = {:.0f}'.format(a, a*8))
print('{:.0f} x  9 = {:.0f}'.format(a, a*9))
print('{:.0f} x 10 = {:.0f}'.format(a, a*10))
print('-' * 12)